namespace Tengu.Business.Commons.Objects
{
    public enum TenguHosts
    {
        AnimeSaturn,
        AnimeUnity,
        None
    }
    public enum TenguLanguages
    {
        Subbed,
        Dubbed,
        None
    }
    public enum TenguStatuses
    {
        InProgress,
        Completed,
        NotReleased,
        Canceled,
        None
    }
    public enum TenguGenres
    {
        ArtiMarziali,
        Avventura,
        Azione,
        Bambini,
        Commedia,
        Demenziale,
        Demoni,
        Drammatico,
        Ecchi,
        Fantasy,
        Gioco,
        Harem,
        Hentai,
        Horror,
        Josei,
        Magia,
        Mecha,
        Militari,
        Mistero,
        Musicale,
        Parodia,
        Polizia,
        Psicologico,
        Romantico,
        Samurai,
        SciFi,
        Scolastico,
        Seinen,
        Sentimentale,
        ShoujoAi,
        Shoujo,
        ShounenAi,
        Shounen,
        SliceOfLife,
        Soprannaturale,
        Spazio,
        Sport,
        Storico,
        Superpoteri,
        Thriller,
        Vampiri,
        Veicoli,
        Yaoi,
        Yuri,
        None
    }
    public enum TenguWeekDays
    {
        Monday,
        Tuesday,
        Wednesday,
        Thursday,
        Friday,
        Saturday,
        Sunday,
        None
    }
}
