name: Master Publish

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/**'
      - 'TenguUI/*'
      
env:
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
  VERSION: 1.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     
     - name: Set outputs
       id: vars
       run: |
         now=$(date "+%s")
         lastMidnight=$(date -d 'today 00:00:00' "+%s")
         startYear=$(date +%s --date "2020-1-1")
         days=$(( ($now-$startYear)/(3600*24) ))
         seconds=$(( ($now-$lastMidnight)/60 ))
         build=$days.$seconds
         
         echo "::set-output name=BUILD::$build"
       
     - name: Check Version and build
       run: echo ${VERSION}.${{ steps.vars.outputs.BUILD }}
     
     - name: Test
       run: |
         dotnet test Tengu.Business.Api/Tengu.Business.API.csproj --configuration Release /p:Version=${VERSION}.${{ steps.vars.outputs.BUILD }}
         dotnet test Tengu.Business.Commons/Tengu.Business.Commons.csproj --configuration Release /p:Version=${VERSION}.${{ steps.vars.outputs.BUILD }}
         dotnet test Tengu.Business.Core/Tengu.Business.Core.csproj --configuration Release /p:Version=${VERSION}.${{ steps.vars.outputs.BUILD }}
         
     - name: Build
       run: |
         dotnet build Tengu.Business.Api/Tengu.Business.API.csproj --configuration Release /p:Version=${VERSION}.${{ steps.vars.outputs.BUILD }}
         dotnet build Tengu.Business.Commons/Tengu.Business.Commons.csproj --configuration Release /p:Version=${VERSION}.${{ steps.vars.outputs.BUILD }}
         dotnet build Tengu.Business.Core/Tengu.Business.Core.csproj --configuration Release /p:Version=${VERSION}.${{ steps.vars.outputs.BUILD }}
         
     - name: Pack
       run: |
         dotnet pack Tengu.Business.Api/Tengu.Business.API.csproj --configuration Release /p:Version=${VERSION}.${{ steps.vars.outputs.BUILD }} --no-build --output .
         dotnet pack Tengu.Business.Commons/Tengu.Business.Commons.csproj --configuration Release /p:Version=${VERSION}.${{ steps.vars.outputs.BUILD }} --no-build --output .
         dotnet pack Tengu.Business.Core/Tengu.Business.Core.csproj --configuration Release /p:Version=${VERSION}.${{ steps.vars.outputs.BUILD }} --no-build --output .
         
     - name: Push
       run: |
         dotnet nuget push Tengu.Business.API.${VERSION}.${{ steps.vars.outputs.BUILD }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
         dotnet nuget push Tengu.Business.Commons.${VERSION}.${{ steps.vars.outputs.BUILD }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}   
         dotnet nuget push Tengu.Business.Core.${VERSION}.${{ steps.vars.outputs.BUILD }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
