name: Master Publish

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]

env:
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     
        
     - name: Set VERSION variable from tag
       run: |
        echo "VERSION=${GITHUB_REF#refs/tags}"
        echo "VERSION=${GITHUB_REF#refs}"
        echo "VERSION=${GITHUB_REF#refs/tags/v/}"
        echo "VERSION=${GITHUB_REF#refs#tags}" >> $GITHUB_ENV
     
     - name: Build
       run: dotnet build --configuration Release
     - name: Test
       run: dotnet test --configuration Release --no-build
       
     - name: Pack
       run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
   
     - name: Push
       run: |
         dotnet nuget push Tengu.Business.API.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
         dotnet nuget push Tengu.Business.Commons.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}   
         dotnet nuget push Tengu.Business.Core.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
